---
title: "Contact"
---

Contact information for the 2026 AAGI Symposium.

If you have a question about the symposium, the organising committee is the best first point of contact. For venue, program or general event enquiries, please use the contacts below.

## Curtin University

Curtin University is the organising node and the host venue for the symposium.

**Sandra Tanz**<br>
[sandra.tanz@curtin.edu.au](mailto:sandra.tanz@curtin.edu.au)

**Braden Thorne**<br>
[braden.thorne@curtin.edu.au](mailto:braden.thorne@curtin.edu.au)

## Administration

For admin-related questions, please contact:

**Fiona Henley**<br>
[fiona.henley@curtin.edu.au](mailto:fiona.henley@curtin.edu.au)

**Nicole Downs**<br>
[nicole.downs@curtin.edu.au](mailto:nicole.downs@curtin.edu.au)

## Adelaide University

**Russell Andrew Edson**<br>
[russell.edson@adelaide.edu.au](mailto:russell.edson@adelaide.edu.au)

**Yanina Giordano**<br>
[yanina.giordano@adelaide.edu.au](mailto:yanina.giordano@adelaide.edu.au)

**Julian Taylor**<br>
[julian.taylor@adelaide.edu.au](mailto:julian.taylor@adelaide.edu.au)

## University of Queensland

**Robert Armstrong**<br>
[r.armstrong1@uq.edu.au](mailto:r.armstrong1@uq.edu.au)

**Sebastian Lopez Marcano**<br>
[s.lopezmarcano@uq.edu.au](mailto:s.lopezmarcano@uq.edu.au)

**Sophy Wang**<br>
[xiaoyi.wang@uq.edu.au](mailto:xiaoyi.wang@uq.edu.au)

**Dinesha Jayawardana**<br>
[dinesha.jayawardana@uq.edu.au](mailto:dinesha.jayawardana@uq.edu.au)

**Vanessa Lopez Corona**<br>
[a.lopezcorona@uq.edu.au](mailto:a.lopezcorona@uq.edu.au)

**Bruno Rafael de Almeida Moreira**<br>
[b.moreira@uq.edu.au](mailto:b.moreira@uq.edu.au)

**Kaiyu Guo**<br>
[kaiyu.guo@uq.edu.au](mailto:kaiyu.guo@uq.edu.au)

If you are unsure who to contact, email the Curtin organising team and your message will be directed to the appropriate person.