---
title: "Program"
---

***
### 🏨 Venue Information
The main symposium is held at the **QT Hotel Perth** at 133 Murray Street in the heart of Perth CBD. Most sessions take place inside the **Murray Room**.

<!-- 🏨 **Venue Note:** The main symposium is held at the **QT Hotel Perth** at 133 Murray Street in the heart of Perth CBD. Most sessions take place inside the **Murray Room**. -->
***

## Schedule at a Glance

| Time Block | Mon 9/11 (Day 0) | Tue 10/11 (Day 1) | Wed 11/11 (Day 2) | Thu 12/11 (Day 3) |
|:---|:---|:---|:---|:---|
| **08:30 - 09:00** | | **Opening by GRDC** | | |
| **09:00 - 10:30** | **Workshop (UQ/WUR)** | **Talks: CU** | **Talks: UQ** | **Talks: AU** |
| **10:30 - 11:00** | ☕ Morning Tea | ☕ Morning Tea | ☕ Morning Tea | ☕ Morning Tea |
| **11:00 - 13:00** | **Workshop (UQ/WUR)** | **Workshop 1** <br> *AI in AAGI: From Tools to Workflows* | **Workshop 2a** <br> *Efficient Trial Design with Speed* | **Workshop 3** <br> *AAGI 2.0: Preparing for the Future* |
| | | **Workshop 2b** <br> *Bioinformatics in AAGI: Projects, Tools and Workflows* | |
| **13:00 - 14:00** | 🥪 Lunch | 🥪 Lunch | 🥪 Lunch | 🏆 **Closing & Awards** |
| **14:00 - 15:30** | **Workshop (UQ/WUR)** | **Industry, Government and Growers (IGG) Session** | **Talks: AAGI partners** | 🥡 Take-away Lunch |
| **15:30 - 16:00** | ☕ Afternoon Tea | ☕ Afternoon Tea | ☕ Afternoon Tea | |
| **16:00 - 16:30** | _Free time_ | _Free time_ | 👭 **HDR Networking Session** | |
| **16:30 - 17:30** | _Free time_ | 📊 **Poster Session** | 👭 **HDR Networking Session** | |
| **17:30 - 18:30** | _Free time_ | 📊 **Poster Session** | _Free time_ | |
| **18:30 - 20:30** | 🥂 **Welcome Mixer** | | 🍽️ **Symposium Dinner** | |

## Daily Schedule

::: {.panel-tabset}

### Day 0: Monday 9/11

| Time | Session | Location |
|:---|:---|:---|
| **09:00 - 10:30** | **Workshop (UQ/WUR)** <br> *Splines / Random Regression* | Murray Room |
| **10:30 - 11:00** | ☕ Morning Tea | Murray Room |
| **11:00 - 13:00** | **Workshop (UQ/WUR)** <br> *GxE* | Murray Room |
| **13:00 - 14:00** | 🥪 Lunch | Murray Room |
| **14:00 - 15:30** | **Workshop (UQ/WUR)** <br> *ODEs* | Murray Room |
| **15:30 - 16:00** | ☕ Afternoon Tea | Murray Room |
| **16:00 - 18:30** | *Free time* | |
| **18:30 - 20:30** | 🥂 **Welcome Mixer** <br> *Networking Social Evening* | QT Rooftop Bar |

### Day 1: Tuesday 10/11

| Time | Session | Location |
|:---|:---|:---|
| **08:30 - 09:00** | **Opening by GRDC** | Murray Room |
| **09:00 - 10:30** | **Talks: CU** | Murray Room |
| **10:30 - 11:00** | ☕ Morning Tea | Murray Room |
| **11:00 - 13:00** | **Workshop 1** <br> *AI in AAGI: From Tools to Workflows* | Murray Room |
| **13:00 - 14:00** | 🥪 Lunch | Murray Room |
| **14:00 - 15:30** | **Industry, Government and Growers (IGG) Session** | Murray Room |
| **15:30 - 16:00** | ☕ Afternoon Tea | Murray Room |
| **16:00 - 16:30** | *Free time* | |
| **16:30 - 18:30** | 📊 **Poster Session** | Murray Room |

### Day 2: Wednesday 11/11

| Time | Session | Location |
|:---|:---|:---|
| **09:00 - 10:30** | **Talks: UQ** | Murray Room |
| **10:30 - 11:00** | ☕ Morning Tea | Murray Room |
| **11:00 - 13:00** | **Workshop 2a** <br> *Efficient Trial Design with Speed* | Murray Room |
| | **Workshop 2b** <br> *Bioinformatics in AAGI: Projects, Tools and Workflows* | Murray Room |
| **13:00 - 14:00** | 🥪 Lunch | Murray Room |
| **14:00 - 15:30** | **Talks: AAGI partners** | Murray Room |
| **15:30 - 16:00** | ☕ Afternoon Tea | Murray Room |
| **16:00 - 17:30** | 👭 **HDR Networking Session** | Murray Room |
| **17:30 - 18:30** | *Free time* | |
| **18:30 - 20:30** | 🍽️ **Symposium Dinner** | *TBA (Offsite Venue)* |

### Day 3: Thursday 12/11

| Time | Session | Location |
|:---|:---|:---|
| **09:00 - 10:30** | **Talks: AU** | Murray Room |
| **10:30 - 11:00** | ☕ Morning Tea | Murray Room |
| **11:00 - 13:00** | **Workshop 3**  <br> *AAGI 2.0: Preparing for the Future*  | Murray Room |
| **13:00 - 14:00** | 🏆 **Closing & AAGI Awards** | Murray Room |
| **14:00+** | 🥡 Take-away Lunch & Departure | Murray Room |

:::

